[mypy-sklearn.*]
ignore_missing_imports = True

[mypy-joblib]
ignore_missing_imports = True

[mypy-agent.repo.financial_record_repository]
disable_error_code = assignment

[mypy-agent.repo.unlabeled_record_repository]
disable_error_code = assignment

[mypy-agent.repo.unlabeled_geoup_repository]
disable_error_code = assignment

[mypy-agent.services.labeling.labeling]
disable_error_code = arg-type